classifier/cic/blueprints/cic_api.py
from flask import Blueprint, request, jsonify, send_file, current_app, make_response
from ..predictor_manager import PredictorManager
from ..utils.file_processing import allowed_file, read_json, process_compressed_file
from ..utils.response_helpers import create_error_response, create_success_response, create_zip_response
import tempfile
import os

api_bp = Blueprint('api', __name__)

@api_bp.route('/classify', methods=['POST'])
def classify():
    request_source = request.headers.get('X-Request-Source', 'unknown')

    # Initialize manifest_dict
    manifest_dict = {}

    # Check for file or JSON data. If no file -> error return manifest
    if 'file' not in request.files and not request.json:
        manifest_dict["Initialization"] = {
            "Status": "Error",
            "Summary": {
                "Data Upload": "Error",
                "Error details": "No file or JSON data uploaded"
            }
        }
        return create_error_response(manifest_dict, 400)

    # Otherwise continue and determine the classification mode
    if 'file' in request.files:
        selected_mode = request.form.get('mode')
    else:
        selected_mode = request.json.get('mode')

    if not selected_mode or selected_mode not in ["WS", "WoS", "M"]:
        manifest_dict["Initialization"] = {
            "Status": "Error",
            "Summary": {
                "Classification Mode Selection": "Error",
                "Error details": "Mode not specified or invalid mode"
            }
        }
        return create_error_response(manifest_dict, 400)

    # Get SRC_PATH from app config
    src_path = current_app.config.get('SRC_PATH')
    if not src_path:
        manifest_dict["Initialization"] = {
            "Status": "Error",
            "Summary": {
                "SRC_PATH setup": "Error",
                "Error details": "SRC_PATH is not set in the application configuration."
            }
        }
        return create_error_response(manifest_dict, 500)

    # Instantiate the predictor manager
    predictor_manager = PredictorManager()
    predictor_manager.SRC_PATH = src_path
    if not predictor_manager.instantiate_predictor(selected_mode):
        manifest_dict = predictor_manager.manifest_dict
        return create_error_response(manifest_dict, 500)

    # Reset manifest_dict for the request
    predictor_manager.manifest_dict = {}

    # Handle file upload
    if 'file' in request.files:
        file = request.files['file']
        filename = file.filename
        if filename == '' or not allowed_file(filename):
            manifest_dict["Data Processing"] = {
                "Filename": filename or "Empty",
                "Status": "Error",
                "Summary": {
                    "Data format check": "Error",
                    "Error details": f"Invalid file type or empty filename. File types supported are: 'json', 'zip', 'tar', 'gz', 'bz2', 'xz', '7z'."
                }
            }
            return create_error_response(manifest_dict, 400)

        # Save file to a temporary dir
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_file_path = os.path.join(temp_dir, filename)
            file.save(temp_file_path)

            # Process the file accordin to its type
            if filename.endswith('.json'):
                try:
                    read_data = read_json(temp_file_path, request_source)
                    # Process data
                    result = predictor_manager.process_data(read_data, filename, from_json=True, request_source=request_source)
                    if result is None:
                        manifest_dict = predictor_manager.manifest_dict
                        return create_error_response(manifest_dict, 500)
                    # Prepare response. 2 scenarios: web or terminal
                    if request_source == 'web-interface':
                        return jsonify(result)
                    else:
                        manifest_dict = predictor_manager.manifest_dict
                        return create_success_response(result, manifest_dict, filename)
                except ValueError as e:
                    manifest_dict["Data Processing"] = {
                        "Filename": filename,
                        "Status": "Error",
                        "Summary": {
                            "Data format check": "Error",
                            "Error details": str(e)
                        }
                    }
                    return create_error_response(manifest_dict, 400)
            else:
                # Handle compressed foiles
                data_list, _ = process_compressed_file(temp_file_path, temp_dir, predictor_manager)
                all_results = []
                for item in data_list:
                    json_data = item['data']
                    json_filename = item['filename']
                    rel_path = item.get('rel_path', json_filename)
                    result = predictor_manager.process_data(json_data, json_filename, from_json=True, request_source=request_source)
                    if result is not None:
                        all_results.append({'filename': json_filename, 'rel_path': rel_path, 'result': result})
                # Prepare response. 2 scenarios: web or terminal
                if request_source == 'web-interface':
                    return create_zip_response(all_results, None)
                else:
                    manifest_dict = predictor_manager.manifest_dict
                    return create_zip_response(all_results, manifest_dict)
    else:
        # Handle JSON data from request body
        data = request.json.get('data')
        if not data:
            manifest_dict["Data Processing"] = {
                "Status": "Error",
                "Summary": {
                    "Data format check": "Error",
                    "Error details": "No data provided"
                }
            }
            return create_error_response(manifest_dict, 400)

        # Process data
        result = predictor_manager.process_data(data, "input_data", from_json=False, request_source=request_source)
        if result is None:
            manifest_dict = predictor_manager.manifest_dict
            return create_error_response(manifest_dict, 500)

        # Prepare response. 2 scenarios: web or terminal
        if request_source == 'web-interface':
            return jsonify(result)
        else:
            manifest_dict = predictor_manager.manifest_dict
            return create_success_response(result, manifest_dict, "result")

classifier/cic/blueprints/web_interface.py
from flask import Blueprint, render_template

interface_bp = Blueprint('interface', __name__)

@interface_bp.route('/')
def index():
    return render_template('index.html', prefix='/cic/')

@interface_bp.route('/classifier')
def classifier_page():
    return render_template('classifier.html', prefix='/cic')

classifier/cic/main.py
import sys
import os
import argparse
from flask import Flask
from cic.blueprints.web_interface import interface_bp
from cic.blueprints.cic_api import api_bp

def create_app(src_path, prefix = "/cic"):
    app = Flask(__name__, static_url_path=prefix+'/static', static_folder="static")

    # Do not sort JSON keys; preserve insertion order for frontend
    app.config["JSON_SORT_KEYS"] = False           # Flask ≤ 2.2
    try:
        app.json.sort_keys = False                 # Flask 2.3+
    except Exception:
        pass

    # Configuration of SRC_PATH in the app
    app.config['SRC_PATH'] = src_path

    # Blueprint registration
    app.register_blueprint(interface_bp, url_prefix=prefix+'/')
    app.register_blueprint(api_bp, url_prefix=prefix+'/api')

    return app


# Create app instance for Gunicorn (uses environment variables)
src_path = os.getenv('SRC_PATH', '/app/classifier/cic/src')
prefix = os.getenv('URL_PREFIX', '/cic')
app = create_app(src_path, prefix)


if __name__ == '__main__':
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description='Run Flask application.')
    parser.add_argument('--src_path', required=True, help='Path to src folder.')
    parser.add_argument('--prefix', required=True, help='Aplication Prefix')
    args = parser.parse_args()
    
    # Override with CLI args if provided
    if args.src_path or args.prefix:
        app = create_app(
            args.src_path or src_path,
            args.prefix or prefix
        )
    
    # Run with Flask dev server
    app.run(host='0.0.0.0', port=5000, debug=False)

classifier/cic/templates/classifier.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CITATION INTENT CLASSIFIER</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/classifier.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="{{ url_for('static', filename='js/conf.js') }}"></script>
    <script>set_prefix('{{prefix}}')</script>

</head>
<body>
    <header class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Citation Intent Classifier – CIC (Alpha release)</a>
      <nav>
        <ul>
          <li><a href="{{ url_for('interface.index') }}">Home</a></li>
          <li><a href="{{ url_for('interface.classifier_page') }}">Classifier</a></li>
          <!--<li><a href="{{prefix}}page-3">About</a></li>-->
        </ul>
      </nav>
    </header>

    <section>
        <h2>Classify Your Sentences</h2>
        <p class="description">
            This is a tool to classify your sentences according to the categories presented in the landing page.</br>
            You can either enter your sentences in the form below, or upload a JSON file containing them.</br>
            The result will be displayed in the form of a table, and you will be able to download it as a JSON file.</br>
            It is <b>important to notice</b> that:
        </p>
        <div class="list-container">
            <ul>
                <li>if you upload a JSON file, you will have to click the "Classify JSON" button,</li>
                <li>if you enter your sentences manually, you will have to click the "Classify" button.</li>
            </ul>
        </div>
        <p>
            In both scenarios, the result will be displayed in the table below, and you will be able to download it as a JSON file.</br>
            Please, do not forget to select your classification mode before classifying your sentences.
        </p>

        <h2>How to use</h2>
        <div class="content-row">
            <div class="left-side">
                <h3>Manually inserted sentences (Manual upload)</h3>
                <p class="description">Enter your sentences below in the form of a list of tuples.</p>
                <div class="example">
                    <p>
                        Each tuple <b>MUST</b> contain both section title and citation context.<br>
                        The format is a LIST, so please do not forget to put squared brackets around it, and
                        the commas to divide the tuples.<br>
                        In case you do not have the section title, it has to be replaced by an empty string.
                    </p>
                    <p>
                        <b>Example:</b><br>
                    </p>
                    <pre class="code-example">
                    <code>
                        [
                            ('Introduction', "In his 1945 essay 'As We May Think',...record [Bush, 1945]."),
                            ('', 'The problem has only ... nine years [Bornmann and Mutz, 2015].'),
                            (..., ...),
                            ...
                        ]
                    </code>
                    </pre>
                </div>
            </div>

            <div class="right-side">
                <h3>Automatically inserted sentences (JSON upload)</h3>
                <p class="description">Or you can upload a JSON file:</p>
                <div class="example">
                    <p>
                        The structure of the JSON file has to follow some rules.</br>
                        Each data entry needs an ID as key, and as value it asks for a dictionary with two keys: 'SECTION' and 'CITATION'.
                        The value of 'SECTION' is a string of the section title, and the value of 'CITATION' is a string of the citation context.</br>
                        For empty elements, the value of 'SECTION' has to be an empty string.
                    </p>
                    <p>
                        <b>Example:</b><br>
                    </p>
                    <pre class="code-example">
                    <code>
                    {
                        ID1:{
                            'SECTION': 'Introduction',
                            'CITATION': 'In his 1945 essay 'As We May Think',...record [Bush, 1945].'
                        },
                        ID2:{
                            'SECTION': '',
                            'CITATION': 'The problem has only ... nine years [Bornmann and Mutz, 2015].'
                        },
                        ID3: ...
                    }
                    </code>
                    </pre>
                </div>
            </div>
        </div>

        <p>Select your classification mode:</p>
        <!-- Here is the switch button for mode selection -->
        <div class="modes">
            <input type="radio" class="mode-input" id="mode1" name="mode" value="M" checked>
            <label class="mode-option" for="mode1">Mixed</label>

            <input type="radio" class="mode-input" id="mode2" name="mode" value="WS">
            <label class="mode-option" for="mode2">With Section Titles</label>

            <input type="radio" class="mode-input" id="mode3" name="mode" value="WoS">
            <label class="mode-option" for="mode3">Without Section Titles</label>
        </div>

        <div class="file-upload">
            <input type="file" id="json-file" name="file" accept=".json">
            <button type="button" id="upload-json-btn">Classify JSON</button>
        </div>


        <form id="classify-form">
            <textarea id="input-text" name="sentences" rows="10" placeholder="[('Section title 1', 'Citation context 1'), ('Section title 2', 'Citation context 2'), ...]"></textarea>
            <button type="button" id="classify-btn">Classify</button>
        </form>

    </section>
    <section>
        <div class="space-holder"></div>
        <div id="loading" style="display:none;">
            <p>Loading...</p>
        </div>
        <div id="result"></div>
        <button type="button" id="download-json-btn" style="display:none;">Download JSON</button>
        <div class="space-holder"></div>
    </section>

    <footer class="footer mt-4 py-3 bg-dark text-white">
      <div class="row" style="padding-top: 50px;">
        <div class="col-lg-4" style="padding: 40px;">
          <img src="{{ url_for('static', filename='img/graspos_white.svg') }}" alt="Company Logo" class="img-fluid mb-2" style="height: 100px;">
        </div>

        <div class="col-lg-4" style="padding: 40px;">
          <img src="{{ url_for('static', filename='img/oc_white.svg') }}" alt="Company Logo" class="img-fluid mb-2" style="height: 150px;">
        </div>

        <div class="col-lg-4" style="padding: 20px;">
          <h5 class="text-uppercase mb-2">GENERAL INFORMATION</h6>
          <ul class="list-unstyled text-small mb-0">
            <li><a class="text-white" href="https://graspos.eu/">About GraspOS</a></li>
            <li><a class="text-white" href="https://opencitations.net">About OpenCitations</a></li>
          </ul>
        </div>
      </div>
      <div class="row" style="padding-top: 30px;">
        <div class="col-lg-12">
          <p class="small mb-0">Copyright © 2023 CITATION INTENT CLASSIFIER – CIC</p>
        </div>
      </div>
    </footer>

    <script src="{{ url_for('static', filename='js/classifier.js') }}"></script>
</body>
</html>

classifier/cic/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CITATION INTENT CLASSIFIER</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
    <!--<link rel="stylesheet" href="/classifier/cic/static/css/index.css">-->
  </head>
  <body>

    <header class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Citation Intent Classifier – CIC (Alpha release)</a>
      <nav>
        <ul>
          <li><a href="{{ url_for('interface.index') }}">Home</a></li>
          <li><a href="{{ url_for('interface.classifier_page') }}">Classifier</a></li>
          <!--<li><a href="{{prefix}}page-3">About</a></li>-->
        </ul>
      </nav>
    </header>

    <section>
      <h1>CITATION INTENT CLASSIFIER – CIC</h1>
      <h2>Project Overview</h2>
      <p>
        This tool has the aim to let you classify citation intents.</br>
        The classification part is carried out by an Ensemble Model,
        which is a combination of three binary classifiers and a meta classifier built
        on top of them.</br>The meta classifier carries out the voting process and
        returns the final classification result.</br>
        Furthermore, a threshold of 90% confidence has been defined to filter out the results
        on which the model is not confident enough.

      </p>
    </section>

    <section>
      <h2>Key Features</h2>
      <p>
        The baseline model surpass the <a href="https://paperswithcode.com/sota/citation-intent-classification-on-scicite">current SOTA Macro-F1 score</a>
        for the citation intent classification task with <a href="https://allenai.org/data/scicite">SciCite dataset</a>.
      </p>
      <p>
        This tool gives you the possibility to classify any number of input sentences given in input in the form of a list of tuples.</br>
        Clearly, higher the number of sentences, higher the time needed to classify all of them and to get back results.</br>
        The tool also gives you the possibility to download the results in JSON format.
      </p>
      <p>
        Finally, you have the possibility to select <b>one of three possible working modes</b>:
      </p>
      <div class="list-container">
        <ul>
          <li><b>With Sections (WS)</b>: select this mode if ALL your sentences have also the title of the section in which the citation is contained;</li>
          <li><b>Without Sections (WoS)</b>: select this mode if NONE of your sentences contains the title of the section in which the citation is, or if you want to try a classification based on the pure semantic of the sentence at hand;</li>
          <li><b>Mixed (M)</b>: select this mode if SOME of your sentences have the title of the section in which the citation is contained, and others not. The tool will carry out the entire filtering process and return you the results.</li>
        </ul>
      </div>


      </p>
    </section>

    <section>
      <h2>How to use the tool</h2>
      <p>
        To use this tool, you have to go to the <a href="{{ url_for('interface.classifier_page') }}">Classifier</a> page</br>
        and select the needed mode through the 3 buttons on top.</br>
        Then, you have to insert your sentences in the form of a list of tuples, or as a JSON file.</br>
        <b><i>It is extremely important to follow the format of the input, otherwise the tool will not work</i></b>.
      </p>
      <p>
        Once you have added all the sentences you want to classify, simply click on the <b>Classify</b> button (or on the <b>Classify JSON</b> button if you uploaded a JSON file).</br>
        The tool will carry out the classification process and return you the results.</br>
        These results will be printed out on screen in an easy to understand format.
      </p>
      <p>
        Additionally, at the end of the classification process, a <b>Download JSON</b> button will appear at the bottom of the page,</br>
        by clicking on it the browser will download a JSON file containing the results.</br>
        <b><i>It is important to note that the time needed to classify all the sentences depends on the number of sentences you have inserted.</i></b>
      </p>
    </section>

    <footer class="footer mt-4 py-3 bg-dark text-white">
      <div class="row" style="padding-top: 50px;">
        <div class="col-lg-4" style="padding: 40px;">
          <img src="{{ url_for('static', filename='img/graspos_white.svg') }}" alt="Company Logo" class="img-fluid mb-2" style="height: 100px;">
        </div>

        <div class="col-lg-4" style="padding: 40px;">
          <img src="{{ url_for('static', filename='img/oc_white.svg') }}" alt="Company Logo" class="img-fluid mb-2" style="height: 150px;">
        </div>

        <div class="col-lg-4" style="padding: 20px;">
          <h5 class="text-uppercase mb-2">GENERAL INFORMATION</h6>
          <ul class="list-unstyled text-small mb-0">
            <li><a class="text-white" href="https://graspos.eu/">About GraspOS</a></li>
            <li><a class="text-white" href="https://opencitations.net">About OpenCitations</a></li>
          </ul>
        </div>
      </div>
      <div class="row" style="padding-top: 30px;">
        <div class="col-lg-12">
          <p class="small mb-0">Copyright © 2023 CITATION INTENT CLASSIFIER – CIC</p>
        </div>
      </div>
    </footer>
  </body>
</html>