extractor/cex/main.py
import logging
import shutil
import zipfile
from datetime import datetime
from concurrent.futures import as_completed, ProcessPoolExecutor
from flask import Flask, render_template, send_from_directory, after_this_request, jsonify, url_for, Blueprint
from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField, IntegerField
from werkzeug.utils import secure_filename
import os
from wtforms.fields.simple import BooleanField
from wtforms.validators import InputRequired, NumberRange
from settings import UPLOAD_FOLDER, DOWNLOAD_FOLDER, SAMPLE_FOLDER
from cleanup import register_cleanup, clean_folder
from utils import get_all_files_by_type, upload_manifest, process_pdf_file

class UploadFileForm(FlaskForm):
    file = FileField("File", validators=[InputRequired()])
    agree = BooleanField("Perform semantic alignment of sections' headings")
    agree2 = BooleanField("Generate JSONld file")
    submit = SubmitField("Process File")
    max_workers = IntegerField('Max Workers', default=1, validators=[NumberRange(min=1, max=50)])


def create_app():
    PREFIX="/cex"

    # change to default as:
    # PREFIX="/"
    app = Flask(__name__, static_url_path=PREFIX+'/static', static_folder="static")

    # Set up logging
    logging.basicConfig(level=logging.DEBUG)

    app.config['SECRET_KEY'] = 'supersecretkey'
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
    app.config['DOWNLOAD_FOLDER'] = DOWNLOAD_FOLDER
    app.config['SAMPLE_FOLDER'] = SAMPLE_FOLDER

    os.makedirs(os.path.join(app.root_path, app.config['DOWNLOAD_FOLDER']), exist_ok=True)
    os.makedirs(os.path.join(app.root_path, app.config['UPLOAD_FOLDER']), exist_ok=True)
    

    @app.route(PREFIX,methods=['GET', "POST"])
    @app.route(PREFIX+'/home', methods=['GET', 'POST'])

    def home():

        clean_folder(os.path.join(app.root_path, app.config['UPLOAD_FOLDER']))
        clean_folder(os.path.join(app.root_path, app.config['DOWNLOAD_FOLDER']))

        os.makedirs('output', exist_ok=True)
        form = UploadFileForm()

        if form.validate_on_submit():

            file = form.file.data
            max_workers = form.max_workers.data
            perform_alignment = form.agree.data
            create_rdf = form.agree2.data
            save_location = os.path.join(app.root_path, app.config['UPLOAD_FOLDER'], secure_filename(file.filename))  # Then save the file
            file.save(save_location)
            download_location = os.path.join(app.root_path, app.config['DOWNLOAD_FOLDER'])  # Then save the file

            pdf_files, unsupported_file_types, targz_fd = get_all_files_by_type(save_location, ".pdf", app.config['UPLOAD_FOLDER'])
            manifest = []
            if pdf_files:
                # Parallel processing of PDF files
                with ProcessPoolExecutor(max_workers=max_workers) as executor:
                    future_to_pdf = {
                        executor.submit(process_pdf_file, pdf, download_location, perform_alignment, create_rdf): pdf for pdf
                        in pdf_files}
                    for future in as_completed(future_to_pdf):
                        pdf = future_to_pdf[future]
                        try:
                            # Collect the result (manifest_info) from each worker process
                            manifest_info = future.result()
                            manifest.append(manifest_info)
                        except Exception as exc:
                            manifest_info = {"filename": os.path.basename(pdf), "status": "error", "error": str(exc)}
                            manifest.append(manifest_info)

            #empty static/files
            upload_folder_path = os.path.join(app.root_path, app.config['UPLOAD_FOLDER'])
            files=[]
            dir=[]
            for entry in os.scandir(upload_folder_path):
                if entry.is_file():
                    files.append(entry.name)
                elif entry.is_dir():
                    dir.append(entry)
            for file in files:
                os.remove(os.path.join(upload_folder_path, file))
            for x in dir:
                shutil.rmtree(x)

            upload_manifest(manifest, download_location)

            current_datetime = datetime.now()
            timestamp = current_datetime.timestamp()

            zip_name = 'processed_pdfs_' + str(timestamp) + '.zip'
            zip_path = os.path.join(download_location, zip_name)

            # Create the zip file
            with zipfile.ZipFile(zip_path, 'w') as zipf:
                for foldername, subfolders, filenames in os.walk(download_location):
                    for filename in filenames:
                        file_path = os.path.join(foldername, filename)
                        # Exclude the zip file itself from being zipped
                        if file_path != zip_path:
                            zipf.write(file_path, os.path.relpath(file_path, download_location))

            # Return the download URL as JSON response
            return jsonify({"download_url": url_for('download_file', filename=zip_name)})

        return render_template('index.html', form=form)


    @app.route(PREFIX+'/sample/<filename>', methods=['GET'])
    def download_sample(filename):
        sample_location = os.path.join(app.root_path, app.config['SAMPLE_FOLDER'])
        return send_from_directory(sample_location, filename, as_attachment=True)

    @app.route(PREFIX+'/downloads/<filename>', methods=['GET'])
    def download_file(filename):
        download_location = os.path.join(app.root_path, app.config['DOWNLOAD_FOLDER'])

        @after_this_request
        def delete_zip(response):
            folder_path = os.path.join(app.root_path, app.config['DOWNLOAD_FOLDER'])
            files = []
            dir = []
            for entry in os.scandir(folder_path):
                if entry.is_file():
                    files.append(entry.name)
                elif entry.is_dir():
                    dir.append(entry)
            for file in files:
                os.remove(os.path.join(folder_path, file))
            for x in dir:
                shutil.rmtree(x)
            return response

        return send_from_directory(download_location, filename, as_attachment=True)

    from api.routes import api_blueprint
    app.register_blueprint(api_blueprint, url_prefix=PREFIX+'/api')

    docs_blueprint = Blueprint('docs', __name__)

    @docs_blueprint.route('/openapi.json')
    def openapi():
        return send_from_directory('docs', 'openapi.json')

    @docs_blueprint.route('/docs')
    def swagger_ui():
        return render_template('swagger.html')
    
    # Register the docs blueprint with the specified prefix
    app.register_blueprint(docs_blueprint, url_prefix=PREFIX)

    return app

# Create the Flask app that works with Gunicorn
app = create_app()
register_cleanup(UPLOAD_FOLDER, DOWNLOAD_FOLDER)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001, debug=False)

extractor/cex/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

</head>
<body>

  <header class="navbar navbar-expand-md navbar-dark bg-dark">
    <a class="navbar-brand" href="#">CITATION EXTRACTOR – CEX</a>
    <a class="navbar-item" href="{{ url_for('docs.swagger_ui') }}" target="_blank" rel="noopener noreferrer">API DOCUMENTATION</a>
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div> -->
    </header>

    <section id="disclaimer">
      <h1>CITATION EXTRACTOR – CEX</h1>
      <p>
        This tool allows you to upload a single PDF file or one archive containing PDFs to process (accepted archives: ZIP, ZST, TAR and TAR.GZ), process it using Grobid and obtain a JSON file containing all the sentences
        where an intext citation is present.
      </p>
      <p>By clicking on “Process File”, Grobid will perform the processing of the input PDFs and as a result a zip folder, containing the Grobid xml, a JSON file composed by the citations sentences, and a JSONLD file, will be automatically downloaded to your machine. Be patient, it will take few seconds.</p>
      <p>N.B. You can process only <b>ONE PDF</b> or <b>ONE ARCHIVE</b> at the time.</p>
      <form method='POST' enctype="multipart/form-data" id="uploadForm">
          {{form.hidden_tag()}}
          {{form.file()}}
          {{form.agree()}} {{form.agree.label}}<br>
          <p class="mt-1">{{form.agree2()}} {{form.agree2.label}}</p>
          {{form.max_workers.label}} {{form.max_workers()}}<br>
          <p class="mt-1">{{form.submit()}}</p>
      </form>
        <div class="mt-2 spinner" id="loadingSpinner"></div>

        <p class="mt-2">You can choose to perform the semantic alignment of the original article's section headings by ticking the box above. When this option is selected, the JSON file, which contains all the sentences with in-text citations, is enriched with a new key called "ALIGNED SECTION." This key stores the aligned section title if it is found.</p>

      <p id="pdflist">
          <h4>Some sample PDFs you can use to test the service:</h4>
          <ul>
              <li><a href="{{ url_for('download_sample', filename='AGR-BIO-SCI_3.pdf') }}">PDF_1</a></li>
              <li><a href="{{ url_for('download_sample', filename='DEC-SCI_31.pdf') }}">PDF_2</a></li>
              <li><a href="{{ url_for('download_sample', filename='MUL_79.pdf') }}">PDF_3</a></li>
              <li><a href="{{ url_for('download_sample', filename='SOC-SCI_103.pdf') }}">PDF_4</a></li>
          </ul>
      </p>
    </section>

    <footer class="footer mt-4 py-3 bg-dark text-white">
      <div class="row" style="padding-top: 50px;">
        <div class="col-lg-4" style="padding: 40px;">
          <img src="{{ url_for('static', filename='img/graspos_white.svg') }}" alt="Company Logo" class="img-fluid mb-2" style="height: 100px;">
        </div>

        <div class="col-lg-4" style="padding: 40px;">
          <img src="{{ url_for('static', filename='img/oc_white.svg') }}" alt="Company Logo" class="img-fluid mb-2" style="height: 150px;">
        </div>

        <div class="col-lg-4" style="padding: 20px;">
          <h5 class="text-uppercase mb-2">GENERAL INFORMATION</h5>
          <ul class="list-unstyled text-small mb-0">
            <li><a class="text-white" href="https://graspos.eu/">About GraspOS</a></li>
            <li><a class="text-white" href="https://opencitations.net">About OpenCitations</a></li>
          </ul>
        </div>
      </div>
      <div class="row" style="padding-top: 30px;">
        <div class="col-lg-12">
          <p class="small mb-0">Copyright © 2023 PDF CITATION EXTRACTOR – CEX</p>
        </div>
      </div>
    </footer>

    <script>
        document.getElementById('uploadForm').onsubmit = function(event) {
            event.preventDefault();  // Prevent form from submitting the traditional way

            // Show spinner
            document.getElementById('loadingSpinner').style.display = 'block';

            // Prepare the form data
            var formData = new FormData(this);

            // Send data to the Flask server using fetch API
            fetch('{{ url_for("home") }}', {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                // Hide spinner
                document.getElementById('loadingSpinner').style.display = 'none';

                // Automatically download the file
                const link = document.createElement('a');
                link.href = data.download_url;
                link.download = '';  // Optional: specify a file name
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            })
            .catch(error => {
                // Hide spinner in case of an error
                document.getElementById('loadingSpinner').style.display = 'none';
                console.error('Error:', error);
            });
        };
    </script>

</body>
</html>

extractor/cex/templates/swagger.html
<!DOCTYPE html>
<html>
  <head>
    <title>API Docs</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js"></script>
    <script>
      SwaggerUIBundle({
        url: "{{ url_for('docs.openapi') }}",
        dom_id: "#swagger-ui",
      });
    </script>
  </body>
</html>